### PR TITLE
allow Symfony 7

### PR DESCRIPTION
**Pull request by tacman**

### CODE REVIEW

**Comment by Ishadijcks** [comment]
Are you actually a consumer of this bundle?

**Comment by tacman** [comment]
No, I'm developing tools to help developers keep their bundles current.  Symfony is an awesome platform, and bundles make it that much more powerful.

**Comment by tacman** [comment]
I'm running into an issue with tests, perhaps you can help me.  Do you know why its failing? 

I added symfony/cache-contracts, but that didn't help.

My PR now has some return types in the code, that was causing problems in the tests.

```


Testing 
E                                                                   1 / 1 (100%)

Time: 00:00.046, Memory: 12.00 MB

There was 1 error:

1) Punch\NevoboBundle\Tests\Service\NevoboClientTest::testGetWords
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "punch_nevobo.service.nevobo_client" has a dependency on a non-existent service "cache.app".

/home/tac/g/tacman/NevoboBundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:116
/home/tac/g/tacman/NevoboBundle/vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:123
```

**Comment by tacman** [comment]
Kudos on this bundle.  Although I don't have a need for this particular API, I have a few bundles that make API calls, but yours is definitely better written.  In particular, I was looking for how to improve my tests, and saw your bundle and wanted to learn from it.  So thank you for releasing it.

**Pull request closed without merging**
